AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Test stack for evmDebugger/TransactionTrace

Parameters:
  Environment:
    Type: String
  SentryDsn:
    Type: String

Resources:
  AnalyzerDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-analyzerStore
      AttributeDefinitions:
        - AttributeName: txHash
          AttributeType: S
        - AttributeName: type#time
          AttributeType: S
      KeySchema:
        - AttributeName: txHash
          KeyType: HASH
        - AttributeName: type#time
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  TransactionTraceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../transaction-trace-api
      Handler: txTraceApi.analyzeTransactionEntrypoint
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          SQS_ANALYZER_URL: !Ref TransactionTraceSqs
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        TransactionTraceApiEvent:
          Type: Api
          Properties:
            Path: /analyzerData/{txHash}/{chainId}
            Method: get
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt TransactionTraceSqs.Arn
    Metadata:
      BuildMethod: makefile

  SrcMapApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../srcmap-api
      Handler: srcMapApi.srcmapApiEntrypoint
      Runtime: nodejs18.x
      Timeout: 180
      Architectures:
        - x86_64
      Environment:
        Variables:
          BUCKET_NAME: !Ref TransactionTraceBucket
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
          REACT_APP_ETHERSCAN_KEY: VTCZHIZD7SD7EP2TMQRDINFV8HWHM243MY
          REACT_APP_POLYGONSCAN_KEY: 93Q76PDC9677CUYFQMHR7S6MI12YKPPVHH
          REACT_APP_ARBITRUMSCAN_KEY: EF6I9YQHU46455ABCHI9EZMR848D38CZK4
      Events:
        SrcMapApiEvent:
          Type: Api
          Properties:
            Path: /srcmap
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Action:
                - s3:*
              Effect: Allow
              Resource:
                - !GetAtt TransactionTraceBucket.Arn
                - !Sub ${TransactionTraceBucket.Arn}/**
    Metadata:
      BuildMethod: makefile

  TransactionTraceSqsDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-sqs-dead-letter

  TransactionTraceSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-sqs
      VisibilityTimeout: 910
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransactionTraceSqsDeadLetter.Arn
        maxReceiveCount: 1

  TransactionTraceBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub ${AWS::StackName}-transaction-trace-bucket

  TransactionTraceProviderFunctionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: transaction-trace-provider-dependencies
      Description: Dependencies for transaction-trace-provider
      ContentUri: ../../transaction-trace-provider/dependencies/
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  TransactionTraceSqsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../transaction-trace-provider
      Handler: src/sqsConsumer.consumeSqsAnalyzeTxEntrypoint
      Runtime: nodejs18.x
      Layers:
          - !Ref TransactionTraceProviderFunctionDepLayer
      Timeout: 900
      MemorySize: 6144
      Architectures:
        - x86_64
      Environment:
        Variables:
          ALCHEMY_KEY: PmDXrefs8kgu3ERHun0yjVkeGrVqs0MQ
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          ANALYZER_DATA_BUCKET_NAME: !Ref TransactionTraceBucket
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionTraceSqs.Arn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 5
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
            - Action:
                - s3:*
              Effect: Allow
              Resource:
                - !GetAtt TransactionTraceBucket.Arn
                - !Sub ${TransactionTraceBucket.Arn}/**
    Metadata:
      BuildMethod: makefile

  TransactionTraceSqsDeadLetterHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../../transaction-trace-provider
      Handler: src/sqsDeadLetterConsumer.consumeSqsAnalyzeTxErrorEntrypoint
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionTraceSqsDeadLetter.Arn
            ScalingConfig:
              MaximumConcurrency: 5
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
    Metadata:
      BuildMethod: makefile

Outputs:
  ApiUrl:
    Description: "API Gateway endpoint URL for test evm debugger stack"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/analyzerData/0xf2a56c4a9edc31fd3a8ed3c3e256d500f548035e84e55df6e1c6b631d91c04f9/1"
