Parameters:
  DomainName:
    Type: String
  CustomBucketName:
    Type: String
    Default: ""
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  DefaultObject:
    Type: String
    Default: "/index.html"
  NotFoundObject:
    Type: String
    Default: "/index.html"
  NotPermittedObject:
    Type: String
    Default: "/index.html"
  Prefix:
    Type: String
    Default: ""
    Description: Limit serving files only to specified prefix
  ExternalCloudFrontOriginAccessIdentity:
    Type: String
    Default: ""

Conditions:
  ShouldCreateCloudFront: !Equals [!Ref ExternalCloudFrontOriginAccessIdentity, ""]
  HasCustomBucketName: !Not [!Equals [!Ref CustomBucketName, ""]]

Resources:
  FrontendBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      BucketName: !If [HasCustomBucketName, !Ref CustomBucketName, !Ref DomainName]
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders:
              - "*"
            AllowedMethods:
              - PUT
              - POST
              - GET
            AllowedOrigins:
              - '*'
      NotificationConfiguration:
        EventBridgeConfiguration:
          EventBridgeEnabled: true

  FrontendOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Condition: ShouldCreateCloudFront
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: !Sub access-identity-${DomainName}

  FrontendCloudFront:
    Type: AWS::CloudFront::Distribution
    Condition: ShouldCreateCloudFront
    Properties:
      DistributionConfig:
        Aliases:
          - !Ref DomainName
        DefaultCacheBehavior:
          AllowedMethods:
            - GET
            - POST
            - HEAD
            - OPTIONS
            - DELETE
            - PUT
            - PATCH
          Compress: True
          ForwardedValues:
            QueryString: False
          DefaultTTL: 86400
          MaxTTL: 31536000
          MinTTL: 0
          TargetOriginId:
            Fn::Join:
              - "-"
              - - S3
                - Ref: FrontendBucket
          ViewerProtocolPolicy: redirect-to-https

        Enabled: True
        HttpVersion: http2
        IPV6Enabled: True
        Origins:
          - DomainName:
              Fn::GetAtt: [FrontendBucket, RegionalDomainName]
            Id:
              Fn::Join:
                - "-"
                - - S3
                  - Ref: FrontendBucket
            S3OriginConfig:
              OriginAccessIdentity:
                Fn::Join:
                  - "/"
                  - - origin-access-identity/cloudfront
                    - Ref: FrontendOriginAccessIdentity
        ViewerCertificate:
          AcmCertificateArn: !Ref CertificateArn
          SslSupportMethod: sni-only
        CustomErrorResponses:
          - ErrorCachingMinTTL: 86000
            ErrorCode: 403
            ResponseCode: 200
            ResponsePagePath: !Ref NotPermittedObject
          - ErrorCachingMinTTL: 86000
            ErrorCode: 404
            ResponseCode: 200
            ResponsePagePath: !Ref NotFoundObject

  FrontendAllowFromCloudFrontBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket:
        Ref: FrontendBucket
      PolicyDocument:
        Statement:
          -
            Sid: 1
            Action:
              - s3:GetObject
            Effect: Allow
            Resource:
              Fn::Join:
                - ""
                -
                  - "arn:aws:s3:::"
                  - Ref: FrontendBucket
                  - !Sub "${Prefix}/*"
            Principal:
              AWS:
                Fn::Join:
                  - " "
                  - - "arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity"
                    - !If [ShouldCreateCloudFront, !Ref FrontendOriginAccessIdentity,  !Ref ExternalCloudFrontOriginAccessIdentity]

  FrontendRoute53:
    Type: AWS::Route53::RecordSet
    Condition: ShouldCreateCloudFront
    Properties:
      AliasTarget:
        DNSName:
          Fn::GetAtt: [FrontendCloudFront, DomainName]
        HostedZoneId: Z2FDTNDATAQYW2 # Static for CloudFront
      HostedZoneId: !Ref HostedZoneId
      Name: !Ref DomainName
      Type: A

Outputs:
  CloudFrontDistributionId:
    Value: !If [ ShouldCreateCloudFront, !Ref FrontendCloudFront, "" ]
  FrontendBucketName:
    Value: !If [ ShouldCreateCloudFront, !Ref DomainName, "" ]
  FrontendBucketArn:
    Value: !GetAtt FrontendBucket.Arn
