Parameters:
  RepositoryName:
    Type: String
  Environment:
    Type: String
  StackArtifactsBucketName:
    Type: String
  GhOIDCProviderArn:
    Type: String

Resources:
  CIFrontendDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RepositoryName}-frontend-deploy-${Environment}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref GhOIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:rumblefishdev/${RepositoryName}:*
      Path: "/"
      Policies:
        - PolicyName: allow-ci-to-update-frontend
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${StackArtifactsBucketName}
                  - !Sub arn:aws:s3:::${StackArtifactsBucketName}/*

  CITranasctionTraceDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RepositoryName}-transaction-trace-deploy-${Environment}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref GhOIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:rumblefishdev/${RepositoryName}:*
      Path: "/"
      Policies:
        - PolicyName: allow-ci-to-update-transactiontrace
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - sqs:Get*
                  - sqs:List*
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - lambda:UpdateFunctionCode
                  - lambda:ListTags
                  - lambda:PublishLayerVersion
                  - lambda:UpdateFunctionConfiguration
                  - lambda:CreateFunction
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceTag/Owner: !Ref RepositoryName
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: arn:aws:cloudformation:us-east-1:aws:transform/Serverless-2016-10-31

  CISrcMapDeployRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${RepositoryName}-srcmap-deploy-${Environment}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref GhOIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: !Sub repo:rumblefishdev/${RepositoryName}:*
      Path: "/"
      Policies:
        - PolicyName: allow-ci-to-update-srcmap
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - cloudformation:*
                  - sqs:Get*
                  - sqs:List*
                  - iam:GetRole
                  - iam:PutRolePolicy
                  - iam:PassRole
                  - lambda:UpdateFunctionCode
                  - lambda:ListTags
                  - lambda:PublishLayerVersion
                  - lambda:UpdateFunctionConfiguration
                  - lambda:CreateFunction
                  - ssm:GetParameter
                  - ssm:GetParameters
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceTag/Owner: !Ref RepositoryName
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: arn:aws:cloudformation:us-east-1:aws:transform/Serverless-2016-10-31