AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  Environment:
    Type: String
  ArtefactsBucketArn:
    Type: String
  OIDCProviderArn:
    Description: Arn for the GitHub OIDC Provider.
    Default: "arn:aws:iam::045028348791:oidc-provider/token.actions.githubusercontent.com"
    Type: String


Resources:
  S3ArtefactsRoleUpload:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub evm-debugger-frontend-github-workflow-${Environment}
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref OIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:rumblefishdev/evm-debugger:*
      Path: "/"
      Policies:
        - PolicyName: upload-to-s3-bucket
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Action:
                  - s3:PutObject
                Resource:
                  - !Ref ArtefactsBucketArn
                  - !Sub ${ArtefactsBucketArn}/**
                  - arn:aws:s3:::artifacts.evm-transaction-trace.rumblefish.com
                  - arn:aws:s3:::artifacts.evm-transaction-trace.rumblefish.com/**
                Effect: Allow
