Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  Environment:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  CertificateArn:
    Type: String
  JsonBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  TaskCpu:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  TaskMemory:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  HardhatImage:
    Type: String

Resources:
  AnalyzerDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-analyzerStore
      AttributeDefinitions:
        -
          AttributeName: txHash
          AttributeType: S
      KeySchema:
        -
          AttributeName: txHash
          KeyType: HASH
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Api:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowOrigin: !Join [ "", [ "'", !Ref ApiGatewayAllowOrigin, "'" ] ]
        AllowHeaders: "'content-type, x-api-key'"
        AllowCredentials: false
      MethodSettings:
        - ResourcePath: "/*"
          HttpMethod: "*"
      Domain:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref Domain
        Route53:
          HostedZoneId: !Ref HostedZoneId

  HardhatCheckStateHandler:
    Type: AWS::Serverless::Function
    Properties:
      Tracing: Active
      CodeUri: ./hardhat.zip
      Handler: dist/script.checkState
      Runtime: nodejs16.x
      Timeout: 600
      MemorySize: 4096
      AutoPublishAlias: HardhatService
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          TMPDIR: '/tmp'
          HARDHAT_VERBOSE: true
          ECS_TASK_DEFINITION: !Ref HardhatTaskDefinition
          CLUSTER_ARN: !GetAtt ECSCluster.Arn
      Events:
        HardhatApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /analyzerData/{txHash}/{chainId}
            Method: GET
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - states:*
              Resource: "*"
            - Action:
                - s3:*
              Effect: Allow
              Resource:
                - "*"
            - Effect: Allow
              Action:
                - ecs:RunTask
                - ecs:DescribeTasks
              Resource:
                - !Ref HardhatTaskDefinition
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**

#  HardhatPrepareDataHandler:
#    Type: AWS::Serverless::Function
#    Properties:
#      CodeUri: ./hardhat.zip
#      Handler: dist/script.prepareTransactionData
#      Runtime: nodejs16.x
#      Environment:
#        Variables:
#          ALCHEMY_KEY: PmDXrefs8kgu3ERHun0yjVkeGrVqs0MQ
#          HARDHAT_VERBOSE: true
#          TMPDIR: '/tmp'
#      Timeout: 600
#      MemorySize: 4096
#      Policies:
#        Statement:
#          - Action:
#              - s3:*
#            Effect: Allow
#            Resource:
#              - "*"

#  HardhatStepFunction:
#    Type: AWS::Serverless::StateMachine
#    Properties:
#      Definition:
#        StartAt: prepareAnalyzerData
#        States:
#          prepareAnalyzerData:
#            Type: Task
#            Resource: !GetAtt HardhatPrepareDataHandler.Arn
#            Parameters:
#              txHash.$: $.detail.requestParameters.txHash
#              chainId.$: $.detail.requestParameters.chainId
#            Next: Done
#          Done:
#            Type: Succeed
#      Tracing:
#        Enabled: true
#      Role: !GetAtt StatesExecutionRole.Arn

  ECSCluster:
    Type: 'AWS::ECS::Cluster'
    Properties:
      ClusterName: HardhatCluster

  HardhatTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: !Sub ${AWS::StackName}-transactionTraceData
      TaskRoleArn: !GetAtt TaskRole.Arn
      ExecutionRoleArn: !GetAtt TaskRole.Arn
      RequiresCompatibilities:
        - FARGATE
      Memory: !Ref TaskMemory
      Cpu: !Ref TaskCpu
      NetworkMode: awsvpc
      ContainerDefinitions:
        - Image: !Ref HardhatImage
          Essential: true
          Memory: !Ref TaskMemory
          Name: hardhat
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref LogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: hardhat

  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      AssumeRolePolicyDocument:
        Statement:
          - Action: sts:AssumeRole
            Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
      Policies:
        - PolicyName: AmazonECSTaskExecutionRolePolicy
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ec2:DescribeNetworkInterfaces
                  - ecs:DescribeTasks
                  - s3:*
                Resource: '*'

  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub ${AWS::StackName}/hardhat

#  StatesExecutionRole:
#    Type: AWS::IAM::Role
#    Properties:
#      AssumeRolePolicyDocument:
#        Version: '2012-10-17'
#        Statement:
#          - Effect: Allow
#            Principal:
#              Service:
#                - Fn::Sub: states.${AWS::Region}.amazonaws.com
#            Action: sts:AssumeRole
#      Path: /
#      Policies:
#        - PolicyName: StatesExecutionPolicy
#          PolicyDocument:
#            Version: '2012-10-17'
#            Statement:
#              - Effect: Allow
#                Action:
#                  - lambda:InvokeFunction
#                Resource: '*'
