Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  CertificateArn:
    Type: String
  TraceBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  AlchemyKey:
    Type: String
  SentryDsn:
    Type: String
  ApiArn:
    Type: String

Resources:
  SrcMapDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-srcmap-actions
      AttributeDefinitions:
        - AttributeName: address
          AttributeType: S
        - AttributeName: type#time
          AttributeType: S
      KeySchema:
        - AttributeName: address
          KeyType: HASH
        - AttributeName: type#time
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  SrcMapApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../srcmap-api
      Handler: srcMapApi.srcmapApiEntrypoint
      Runtime: nodejs18.x
      Timeout: 180
      MemorySize: 256
      Architectures:
        - x86_64
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref SrcMapDataTable
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        TransactionTraceApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref ApiArn
            Path: /srcmap-api
            Method: post
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt SrcMapDataTable.Arn
                - !Sub ${SrcMapDataTable.Arn}/**
    Metadata:
      BuildMethod: makefile
