Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  JsonBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  TaskCpu:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  TaskMemory:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  TransactionTraceProviderImage:
    Type: String
  HardhatForkingUrl:
    Type: String
  Subnets:
    Type: String

Resources:

  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref JsonBucketName

  TransactionTraceService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./transaction-trace-service.yml
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        Domain: !Ref Domain
        CertificateArn: !Ref CertificateArn
        JsonBucketName: !Ref JsonBucketName
        ApiGatewayAllowOrigin: !Ref ApiGatewayAllowOrigin
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        TransactionTraceProviderImage: !Ref TransactionTraceProviderImage
        HardhatForkingUrl: !Ref HardhatForkingUrl
        Subnets: !Ref Subnets
