Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  JsonBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  AlchemyKey:
    Type: String
  SentryDsn:
    Type: String
  GhOIDCProviderArn:
    Type: String
  CloudfrontDistributionArn:
    Type: String

Resources:
  Frontend:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref JsonBucketName
        GhOIDCProviderArn: !Ref GhOIDCProviderArn
        CloudfrontDistributionArn: !Ref CloudfrontDistributionArn

  TransactionTraceService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./transaction-trace-service.yml
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        Domain: !Ref Domain
        CertificateArn: !Ref CertificateArn
        JsonBucketName: !Ref JsonBucketName
        ApiGatewayAllowOrigin: !Ref ApiGatewayAllowOrigin
        AlchemyKey: !Ref AlchemyKey
        SentryDsn: !Ref SentryDsn
        GhOIDCProviderArn: !Ref GhOIDCProviderArn
