Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  JsonBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  TaskCpu:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  TaskMemory:
    Type: String
    Description: See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html
  HardhatImage:
    Type: String

Resources:

  HardhatService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./hardhat.yml
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        Domain: !Ref Domain
        CertificateArn: !Ref CertificateArn
        JsonBucketName: !Ref JsonBucketName
        ApiGatewayAllowOrigin: !Ref ApiGatewayAllowOrigin
        TaskCpu: !Ref TaskCpu
        TaskMemory: !Ref TaskMemory
        HardhatImage: !Ref HardhatImage
