Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  CertificateArn:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  TraceBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  AlchemyKey:
    Type: String
  SentryDsn:
    Type: String
  GhOIDCProviderArn:
    Type: String
  StackArtifactsBucketName:
    Type: String
  RepositoryName:
    Type: String
  FrontendBucketName:
    Type: String
  FrontendExternalCloudFrontOriginAccessIdentity:
    Type: String

Resources:
  TraceBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        HostedZoneId: !Ref HostedZoneId
        DomainName: !Ref TraceBucketName

  FrontendBucket:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./frontend.yml
      Parameters:
        CertificateArn: !Ref CertificateArn
        HostedZoneId: !Ref HostedZoneId
        DomainName: "stage-front.evmdebugger.rumblefish.dev"
        CustomBucketName: !Ref FrontendBucketName
        ExternalCloudFrontOriginAccessIdentity: !Ref FrontendExternalCloudFrontOriginAccessIdentity

  TransactionTraceService:
    Type: AWS::Serverless::Application
    Properties:
      Location: ./services.yml
      Parameters:
        Environment: !Ref Environment
        HostedZoneId: !Ref HostedZoneId
        Domain: !Ref Domain
        CertificateArn: !Ref CertificateArn
        TraceBucketName: !Ref TraceBucketName
        ApiGatewayAllowOrigin: !Ref ApiGatewayAllowOrigin
        AlchemyKey: !Ref AlchemyKey
        SentryDsn: !Ref SentryDsn

#  CIUploadRoleEvmDebugger:
#    Type: AWS::IAM::Role
#    Properties:
#      RoleName: !Sub ${RepositoryName}-github-workflow-${Environment}
#      AssumeRolePolicyDocument:
#        Statement:
#          - Effect: Allow
#            Action: sts:AssumeRoleWithWebIdentity
#            Principal:
#              Federated:
#                - !Ref  GhOIDCProviderArn
#            Condition:
#              StringEquals:
#                token.actions.githubusercontent.com:aud: sts.amazonaws.com
#              StringLike:
#                token.actions.githubusercontent.com:sub: !Sub repo:rumblefishdev/${RepositoryName}:*
#      Path: "/"
#      Policies:
#        - PolicyName: allow-ci-to-update-stack-packages
#          PolicyDocument:
#            Version: "2012-10-17"
#            Statement:
#              - Effect: Allow
#                Action:
#                  - s3:*
#                Resource:
#                  - !Sub arn:aws:s3:::${StackArtifactsBucketName}
#                  - !Sub arn:aws:s3:::${StackArtifactsBucketName}/*
#              - Effect: Allow
#                Action:
#                  - cloudformation:*
#                  - sqs:Get*
#                  - sqs:List*
#                  - iam:GetRole
#                  - iam:PutRolePolicy
#                  - lambda:UpdateFunctionCode
#                  - lambda:ListTags
#                  - lambda:PublishLayerVersion
#                  - lambda:UpdateFunctionConfiguration
#                  - lambda:CreateFunction
#                  - ssm:GetParameter
#                  - ssm:GetParameters
#                Resource: "*"
#                Condition:
#                  StringEquals:
#                    aws:ResourceTag/Owner: !Ref RepositoryName
#              - Effect: Allow
#                Action:
#                  - cloudformation:*
#                Resource: arn:aws:cloudformation:us-east-1:aws:transform/Serverless-2016-10-31
