Transform: AWS::Serverless-2016-10-31
AWSTemplateFormatVersion: '2010-09-09'

Parameters:
  Environment:
    Type: String
  HostedZoneId:
    Type: String
  Domain:
    Type: String
  CertificateArn:
    Type: String
  TraceBucketName:
    Type: String
  ApiGatewayAllowOrigin:
    Type: String
  AlchemyKey:
    Type: String
  SentryDsn:
    Type: String
  GhOIDCProviderArn:
    Type: String
  EvmDebuggerArtifactsBucketName:
    Type: String
    Default: artifacts.evm-transaction-trace.rumblefish.com

Resources:
  AnalyzerDataTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Sub ${AWS::StackName}-analyzer-store
      AttributeDefinitions:
        - AttributeName: txHash
          AttributeType: S
        - AttributeName: type#time
          AttributeType: S
      KeySchema:
        - AttributeName: txHash
          KeyType: HASH
        - AttributeName: type#time
          KeyType: RANGE
      ProvisionedThroughput:
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5

  Api:
    Type: AWS::Serverless::Api
    Name: !Sub ${AWS::StackName}-api
    Properties:
      StageName: !Ref Environment
      Cors:
        AllowMethods: "'POST, GET, OPTIONS'"
        AllowOrigin: !Join ['', ["'", !Ref ApiGatewayAllowOrigin, "'"]]
        AllowHeaders: "'content-type, x-api-key'"
        AllowCredentials: false
      MethodSettings:
        - ResourcePath: '/*'
          HttpMethod: '*'
      Domain:
        CertificateArn: !Ref CertificateArn
        DomainName: !Ref Domain
        Route53:
          HostedZoneId: !Ref HostedZoneId

  TransactionTraceSqsDeadLetter:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-sqs-dead-letter

  TransactionTraceSqs:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: !Sub ${AWS::StackName}-sqs
      VisibilityTimeout: 910
      RedrivePolicy:
        deadLetterTargetArn: !GetAtt TransactionTraceSqsDeadLetter.Arn
        maxReceiveCount: 1

  TransactionTraceFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../transaction-trace-api
      Handler: txTraceApi.analyzeTransactionEntrypoint
      Runtime: nodejs18.x
      Timeout: 30
      MemorySize: 128
      Architectures:
        - x86_64
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          SQS_ANALYZER_URL: !Ref TransactionTraceSqs
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        TransactionTraceApiEvent:
          Type: Api
          Properties:
            RestApiId: !Ref Api
            Path: /analyzerData/{txHash}/{chainId}
            Method: get
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:GetItem
                - dynamodb:PutItem
                - dynamodb:Query
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
            - Effect: Allow
              Action:
                - sqs:SendMessage
              Resource:
                - !GetAtt TransactionTraceSqs.Arn
    Metadata:
      BuildMethod: makefile

  TransactionTraceProviderFunctionDepLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: transaction-trace-provider-dependencies
      Description: Dependencies for transaction-trace-provider
      ContentUri: ../transaction-trace-provider/dependencies/
      CompatibleRuntimes:
        - nodejs18.x
      LicenseInfo: 'MIT'
      RetentionPolicy: Retain
    Metadata:
      BuildMethod: makefile

  TransactionTraceSqsHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../transaction-trace-provider
      Handler: src/sqsConsumer.consumeSqsAnalyzeTxEntrypoint
      Runtime: nodejs18.x
      Layers:
        - !Ref TransactionTraceProviderFunctionDepLayer
      Timeout: 900
      MemorySize: 6144
      Architectures:
        - x86_64
      Environment:
        Variables:
          ALCHEMY_KEY: !Ref AlchemyKey
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          ANALYZER_DATA_BUCKET_NAME: !Ref TraceBucketName
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionTraceSqs.Arn
            BatchSize: 1
            ScalingConfig:
              MaximumConcurrency: 5
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
            - Action:
                - s3:*
              Effect: Allow
              Resource:
                - !Sub arn:aws:s3:::${TraceBucketName}
                - !Sub arn:aws:s3:::${TraceBucketName}/**

    Metadata:
      BuildMethod: makefile

  TransactionTraceSqsDeadLetterHandlerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ../transaction-trace-provider
      Handler: src/sqsDeadLetterConsumer.consumeSqsAnalyzeTxErrorEntrypoint
      Runtime: nodejs18.x
      Architectures:
        - x86_64
      Environment:
        Variables:
          ANALYZER_DATA_TABLE_NAME: !Ref AnalyzerDataTable
          ENVIRONMENT: !Ref Environment
          SENTRY_DSN: !Ref SentryDsn
      Events:
        SqsEvent:
          Type: SQS
          Properties:
            Queue: !GetAtt TransactionTraceSqsDeadLetter.Arn
            ScalingConfig:
              MaximumConcurrency: 5
      Policies:
        - Statement:
            - Effect: Allow
              Action:
                - iam:PassRole
              Resource:
                - '*'
            - Effect: Allow
              Action:
                - dynamodb:PutItem
              Resource:
                - !GetAtt AnalyzerDataTable.Arn
                - !Sub ${AnalyzerDataTable.Arn}/**
    Metadata:
      BuildMethod: makefile

  CIUploadRoleEvmDebugger:
    Type: AWS::IAM::Role
    Properties:
      RoleName: !Sub ${Domain}-github-workflow
#      ManagedPolicyArns:
#        - arn:aws:iam::aws:policy/AWSCloudFormationFullAccess
##        - arn:aws:iam::aws:policy/IAMFullAccess
#        - arn:aws:iam::aws:policy/AmazonS3FullAccess
#        - arn:aws:iam::aws:policy/AWSLambda_FullAccess
#        - arn:aws:iam::aws:policy/AmazonAPIGatewayAdministrator
#        - arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess
#        - arn:aws:iam::aws:policy/AmazonSQSFullAccess
      AssumeRolePolicyDocument:
        Statement:
          - Effect: Allow
            Action: sts:AssumeRoleWithWebIdentity
            Principal:
              Federated:
                - !Ref  GhOIDCProviderArn
            Condition:
              StringEquals:
                token.actions.githubusercontent.com:aud: sts.amazonaws.com
              StringLike:
                token.actions.githubusercontent.com:sub: repo:rumblefishdev/evm-debugger:*
      Path: "/"
      Policies:
        - PolicyName: allow-ci-to-update-sam-packages
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: Allow
                Action:
                  - s3:*
                Resource:
                  - !Sub arn:aws:s3:::${EvmDebuggerArtifactsBucketName}
                  - !Sub arn:aws:s3:::${EvmDebuggerArtifactsBucketName}/*
              - Effect: Allow
                Action:
                  - cloudformation:*
                Resource: "*"
                Condition:
                  StringEquals:
                    aws:ResourceTag/Owner: evm-debugger
