Transform: AWS::Serverless-2016-10-31
Parameters:
  Environment:
    Type: String
  SentryDsn:
    Type: String
  TraceBucketName:
    Type: String
  CompilerVersion:
    Type: String
Resources:
  SrcMapCompilerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}
      CodeUri: ../../srcmap-compiler
      Handler: srcMapCompiler.srcmapCompilerEntrypoint
      Runtime: nodejs18.x
      Timeout: 600
      MemorySize: 512
      Architectures:
      - x86_64
      Environment:
        Variables:
          BUCKET_NAME:
            Ref: TraceBucketName
          ENVIRONMENT:
            Ref: Environment
          SENTRY_DSN:
            Ref: SentryDsn
      Policies:
      - Statement:
        - Effect: Allow
          Action:
          - iam:PassRole
          Resource:
          - '*'
        - Effect: Allow
          Action:
          - s3:*
          Resource:
          - Fn::Sub: arn:aws:s3:::${TraceBucketName}/**
    Metadata:
      BuildMethod: makefile
      SamResourceId: SrcMapCompilerFunction
  SrcMapCompiler:
    Type: AWS::SSM::Parameter
    Properties:
      Name:
        Fn::Sub: /evm-debugger/${Environment}/${CompilerVersion}
      Type: String
      Value:
        Ref: SrcMapCompilerFunction
    Metadata:
      SamResourceId: SrcMapCompiler
