export enum StoreKeys {
  ACTIVE_BLOCK = 'activeBlock',
  ANALYZER = 'analyzer',
  DISASSEMBLED_BYTECODES = 'disassembledBytecodes',
  TRANSACTION_INFO = 'transactionInfo',
  SIGHASH = 'sighash',
  STRUCT_LOGS = 'structlogs',
  ACTIVE_STRUCT_LOG = 'activeStructLog',
  TRACE_LOGS = 'traceLogs',
  INSTRUCTIONS = 'instructions',
  UI = 'ui',
  TRANSACTION_CONFIG = 'transactionConfig',
  ABIS = 'abis',
  ACTIVE_LINE = 'activeLine',
  YUL_NODES = 'yulNodes',
  SOURCE_FILES = 'sourceFiles',
  CONTRACT_BASE = 'contractBase',
  CONTRACT_RAW = 'contractRaw',
}
