export enum StoreKeys {
  SOURCE_CODES = 'sourceCodes',
  SOURCE_MAPS = 'sourceMaps',
  ACTIVE_BLOCK = 'activeBlock',
  ANALYZER = 'analyzer',
  BYTECODES = 'bytecodes',
  RAW_TX_DATA = 'rawTxData',
  SIGHASH = 'sighash',
  STRUCT_LOGS = 'structlogs',
  ACTIVE_STRUCT_LOG = 'activeStructLog',
  TRACE_LOGS = 'traceLogs',
  CONTRACT_NAMES = 'contractNames',
  ACTIVE_SOURCE_FILE = 'sourceFiles',
  INSTRUCTIONS = 'instructions',
  UI = 'ui',
}
