// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.

import type { Document } from '@contentful/rich-text-types'
import type { Asset, Entry } from 'contentful'

export interface IActionButtonFields {
  /** label */
  label: string

  /** anchorId */
  anchorId?: string | undefined

  /** top */
  top?: number | undefined
}

export interface IActionButton extends Entry<IActionButtonFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'actionButton'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IAnchorFields {
  /** id */
  id: string
}

export interface IAnchor extends Entry<IAnchorFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'anchor'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IAuthorFields {
  /** Name */
  name: string

  /** Position */
  position: string

  /** Avatar */
  avatar?: Asset | undefined
}

export interface IAuthor extends Entry<IAuthorFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'author'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IBackgroundImageFields {
  /** title */
  title?: string | undefined

  /** image */
  image?: Asset | undefined

  /** color */
  color?: string | undefined

  /** left */
  left?: number | undefined

  /** top */
  top?: number | undefined

  /** height */
  height?: number | undefined

  /** align */
  align: 'left' | 'right'

  /** topUnit */
  topUnit: 'px' | '%'
}

export interface IBackgroundImage extends Entry<IBackgroundImageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'backgroundImage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IBlogPostFields {
  /** Title */
  title: string

  /** Slug */
  slug: string

  /** PubDate */
  pubDate: string

  /** Category */
  category: string[]

  /** Image */
  image: Asset

  /** imageFitContain */
  imageFitContain?: boolean | undefined

  /** FacebookImage */
  facebookImage?: Asset | undefined

  /** Authors */
  authors: IAuthor[]

  /** Content */
  content?: Document | undefined

  /** ShortContent */
  shortContent: Document

  /** TimeToRead */
  timeToRead: number

  /** homePageTag */
  homePageTag?: IBlogTag | undefined
}

/** Article on our blog */

export interface IBlogPost extends Entry<IBlogPostFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'blogPost'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IBlogTagFields {
  /** tag */
  tag?: string | undefined
}

export interface IBlogTag extends Entry<IBlogTagFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'blogTag'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IBusinessVerticalFields {
  /** title */
  title: string

  /** slug */
  slug: string

  /** main description */
  mainDescription?: string | undefined

  /** ServicesBlockHeaderRichDescriptionPhoto */
  servicesBlockHeaderRichDescriptionPhoto?:
    | IServicesBlockHeaderRichDescriptionPhoto[]
    | undefined

  /** ServicesBlockHeaderDescriptionPhoto */
  servicesBlockHeaderDescriptionPhoto?:
    | IServicesBlockHeaderDescriptionPhoto[]
    | undefined

  /** ServicesBlockHeaderDescription */
  servicesBlockHeaderDescription?: IServicesBlockHeaderDescription[] | undefined

  /** description */
  description: string

  /** card description */
  cardDescription: string

  /** long description */
  longDescription: Document

  /** service icon */
  serviceIcon: Asset

  /** service headline */
  serviceHeadline: string

  /** home page icon */
  homePageIcon: Asset

  /** Gains */
  gains: IGain[]

  /** facebook image */
  facebookImage: Asset

  /** ribbon */
  ribbon: Asset

  /** modal ribbon */
  modalRibbon: Asset
}

export interface IBusinessVertical extends Entry<IBusinessVerticalFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'businessVertical'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ICaseStudyFields {
  /** client */
  client: string

  /** companyName */
  companyName: string

  /** slug */
  slug: string

  /** title */
  title: string

  /** subtitle */
  subtitle?: string | undefined

  /** logo */
  logo: Asset

  /** image */
  image: Asset

  /** facebookImage */
  facebookImage?: Asset | undefined

  /** Collaboration timeframe */
  collaborationTimeframe?: string | undefined

  /** Technology */
  technology?: string | undefined

  /** Team size */
  teamSize?: string | undefined

  /** Services */
  services?: string | undefined

  /** content1 */
  content1: Document

  /** clientColor */
  clientColor: string

  /** content2 */
  content2?: Document | undefined

  /** content3 */
  content3?: Document | undefined

  /** services image */
  servicesImage: Asset

  /** card description */
  cardDescription: string

  /** Tags */
  tags?: ITag[] | undefined
}

export interface ICaseStudy extends Entry<ICaseStudyFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'caseStudy'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ICaseStudyTestimonialFields {
  /** title */
  title?: string | undefined

  /** content */
  content: string

  /** author */
  author: IAuthor

  /** style */
  style: 'normal' | 'inline'
}

/** Testimonial to be included inline into CaseStudy Rich text areas */

export interface ICaseStudyTestimonial
  extends Entry<ICaseStudyTestimonialFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'caseStudyTestimonial'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ICodeSnippetFields {
  /** title */
  title?: string | undefined

  /** body */
  body: string

  /** language */
  language: 'javascript' | 'bash' | 'json' | 'yaml' | 'solidity' | 'kotlin'
}

export interface ICodeSnippet extends Entry<ICodeSnippetFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'codeSnippet'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ICurrentOpeningsFields {
  /** title */
  title?: string | undefined

  /** jobPosting */
  jobPosting: IJobPosting[]
}

export interface ICurrentOpenings extends Entry<ICurrentOpeningsFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'currentOpenings'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IDeliveryProcessFields {
  /** title */
  title: string

  /** Headline */
  headline: string

  /** processes */
  processes: IProcess[]

  /** ribbon */
  ribbon: Asset
}

export interface IDeliveryProcess extends Entry<IDeliveryProcessFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'deliveryProcess'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IDownloadButtonFields {
  /** title */
  title: string

  /** label */
  label: string

  /** target */
  target?: Asset | undefined
}

export interface IDownloadButton extends Entry<IDownloadButtonFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'downloadButton'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IGainFields {
  /** title */
  title: string

  /** gain icon */
  gainIcon: Asset

  /** description */
  description: Document
}

/** 'What you can gain' part from service page */

export interface IGain extends Entry<IGainFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'gain'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IGridBlockFields {
  /** title */
  title?: string | undefined

  /** content */
  content: Document

  /** backgroundImage */
  backgroundImage?: IBackgroundImage | undefined

  /** xs */
  xs: number

  /** sm */
  sm: number

  /** md */
  md: number

  /** backgroundColor */
  backgroundColor?: string | undefined

  /** backgroundRadius */
  backgroundRadius?: number | undefined
}

export interface IGridBlock extends Entry<IGridBlockFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'gridBlock'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IHubspotFormFields {
  /** title */
  title?: string | undefined

  /** portalId */
  portalId: string

  /** formGuid */
  formGuid?: string | undefined

  /** successUrl */
  successUrl: string

  /** submitText */
  submitText: string
}

export interface IHubspotForm extends Entry<IHubspotFormFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'hubspotForm'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IIconCardFields {
  /** image */
  image?: IImage | undefined

  /** title */
  title?: string | undefined

  /** description */
  description?: string | undefined

  /** lg */
  lg: number

  /** md */
  md: number

  /** sm */
  sm: number

  /** xs */
  xs: number
}

export interface IIconCard extends Entry<IIconCardFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'iconCard'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IIconCardsCollectionFields {
  /** name */
  name?: string | undefined

  /** items */
  items?: IIconCard[] | undefined
}

export interface IIconCardsCollection
  extends Entry<IIconCardsCollectionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'iconCardsCollection'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IIconHeadlineDescriptionFields {
  /** icon */
  icon?: Asset | undefined

  /** headline */
  headline?: string | undefined

  /** description */
  description?: string | undefined
}

export interface IIconHeadlineDescription
  extends Entry<IIconHeadlineDescriptionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'iconHeadlineDescription'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImageFields {
  /** title */
  title?: string | undefined

  /** image */
  image: Asset

  /** width */
  width: number

  /** height */
  height: number

  /** align */
  align?: 'left' | 'center' | 'right' | undefined
}

export interface IImage extends Entry<IImageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'image'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImagesGridFields {
  /** title */
  title?: string | undefined

  /** Images */
  images?: Asset[] | undefined
}

/** Display a grid of images within a RichText field */

export interface IImagesGrid extends Entry<IImagesGridFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'imagesGrid'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IImageSliderFields {
  /** title */
  title?: string | undefined

  /** images */
  images?: Asset[] | undefined
}

export interface IImageSlider extends Entry<IImageSliderFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'imageSlider'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IInstagramPostReferenceFields {
  /** uri */
  uri: string
}

export interface IInstagramPostReference
  extends Entry<IInstagramPostReferenceFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'instagramPostReference'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IInstagramPostsFields {
  /** title */
  title?: string | undefined

  /** posts */
  posts?: IInstagramPostReference[] | undefined
}

export interface IInstagramPosts extends Entry<IInstagramPostsFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'instagramPosts'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IJobPageFields {
  /** job title info */
  jobTitleInfo?: string | undefined

  /** job title */
  jobTitle?: Document | undefined

  /** ribbon */
  ribbon?: Asset | undefined

  /** salary */
  salary?: string | undefined

  /** technologies list */
  technologiesList?: string[] | undefined

  /** great if you know list */
  greatIfYouKnowList?: string[] | undefined

  /** important traits list */
  importantTraitsList?: string[] | undefined

  /** what you will do */
  whatYouWillDo?: string[] | undefined

  /** our offer also include list */
  ourOfferAlsoIncludeList?: IIconHeadlineDescription[] | undefined

  /** how we work list */
  howWeWorkList?: string[] | undefined

  /** a few words description */
  aFewWordsDescription?: string | undefined

  /** how we recruit list */
  howWeRecruitList?: INumberHeadlineDescription[] | undefined
}

export interface IJobPage extends Entry<IJobPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'jobPage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IJobPostingFields {
  /** title */
  title: string

  /** slug */
  slug?: string | undefined

  /** salary */
  salary?: string | undefined

  /** team */
  team?: string | undefined

  /** location */
  location?: string | undefined

  /** icon */
  icon?: Asset | undefined

  /** facebookImage */
  facebookImage?: Asset | undefined

  /** job page */
  jobPage: IJobPage
}

export interface IJobPosting extends Entry<IJobPostingFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'jobPosting'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ILandingPageFields {
  /** title */
  title?: string | undefined

  /** slug */
  slug?: string | undefined

  /** description */
  description?: string | undefined

  /** blocks */
  blocks?: IGridBlock[] | undefined

  /** facebookImage */
  facebookImage?: Asset | undefined
}

export interface ILandingPage extends Entry<ILandingPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'landingPage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ILinkImageFields {
  /** title */
  title: string

  /** image */
  image?: Asset | undefined

  /** type */
  type: 'internal' | 'external'

  /** url */
  url: string
}

export interface ILinkImage extends Entry<ILinkImageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'linkImage'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface INumberHeadlineDescriptionFields {
  /** number */
  number?: number | undefined

  /** headline */
  headline?: string | undefined

  /** description */
  description?: string | undefined
}

export interface INumberHeadlineDescription
  extends Entry<INumberHeadlineDescriptionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'numberHeadlineDescription'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPageFields {
  /** title */
  title: string

  /** description */
  description: string

  /** pathname */
  pathname: string

  /** category */
  category: string[]

  /** blocks */
  blocks?: IGridBlock[] | undefined

  /** backgroundImage */
  backgroundImage?: IBackgroundImage | undefined

  /** facebookImage */
  facebookImage?: Asset | undefined

  /** outerColumnGapXS */
  outerColumnGapXs?: number | undefined

  /** outerColumnGapSM */
  outerColumnGapSm?: number | undefined

  /** outerColumnGapMD */
  outerColumnGapMd?: number | undefined

  /** spacing */
  spacing?: number | undefined
}

export interface IPage extends Entry<IPageFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'page'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPersonCardFields {
  /** picture */
  picture: IImage

  /** description */
  description: string

  /** email */
  email?: string | undefined

  /** role */
  role?: string | undefined

  /** content */
  content?: string | undefined

  /** linkedInProfile */
  linkedInProfile?: string | undefined
}

export interface IPersonCard extends Entry<IPersonCardFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'personCard'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IPolicyFields {
  /** test */
  test?: string | undefined

  /** slug */
  slug?: string | undefined
}

export interface IPolicy extends Entry<IPolicyFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'policy'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IProcessFields {
  /** title */
  title: string

  /** process description */
  processDescription: string

  /** process icon */
  processIcon: Asset
}

export interface IProcess extends Entry<IProcessFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'process'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesFields {
  /** title */
  title: string

  /** slug */
  slug: string

  /** main description */
  mainDescription?: string | undefined

  /** ServicesBlockHeaderRichDescriptionPhoto */
  servicesBlockHeaderRichDescriptionPhoto?:
    | IServicesBlockHeaderRichDescriptionPhoto[]
    | undefined

  /** ServicesBlockHeaderDescriptionPhoto */
  servicesBlockHeaderDescriptionPhoto?:
    | IServicesBlockHeaderDescriptionPhoto[]
    | undefined

  /** ServicesBlockHeaderDescription */
  servicesBlockHeaderDescription?: IServicesBlockHeaderDescription[] | undefined

  /** description */
  description: string

  /** card description */
  cardDescription: string

  /** long description */
  longDescription: Document

  /** service icon */
  serviceIcon: Asset

  /** service headline */
  serviceHeadline: string

  /** home page icon */
  homePageIcon: Asset

  /** Gains */
  gains: IGain[]

  /** facebook image */
  facebookImage?: Asset | undefined

  /** ribbon */
  ribbon: Asset

  /** modal ribbon */
  modalRibbon: Asset
}

/** services description */

export interface IServices extends Entry<IServicesFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'services'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesTechnologiesElementFields {
  /** technology element */
  technologyElement?: string | undefined

  /** technology link */
  technologyLink?: string | undefined
}

/** single technology displayed in Services */

export interface IServicesTechnologiesElement
  extends Entry<IServicesTechnologiesElementFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'services-technologies-element'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesBannerFields {
  /** header */
  header?: Document | undefined

  /** items */
  items?: IServicesBannerItem[] | undefined

  /** buttonFirstText */
  buttonFirstText?: string | undefined

  /** buttonSecondText */
  buttonSecondText?: string | undefined
}

export interface IServicesBanner extends Entry<IServicesBannerFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesBanner'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesBannerItemFields {
  /** title */
  title?: string | undefined

  /** link */
  link?: string | undefined
}

export interface IServicesBannerItem extends Entry<IServicesBannerItemFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesBannerItem'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesBlockHeaderDescriptionFields {
  /** header */
  header?: string | undefined

  /** description */
  description?: string | undefined
}

export interface IServicesBlockHeaderDescription
  extends Entry<IServicesBlockHeaderDescriptionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesBlockHeaderDescription'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesBlockHeaderDescriptionPhotoFields {
  /** header */
  header?: string | undefined

  /** description */
  description?: string | undefined

  /** photo */
  photo?: Asset | undefined
}

export interface IServicesBlockHeaderDescriptionPhoto
  extends Entry<IServicesBlockHeaderDescriptionPhotoFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesBlockHeaderDescriptionPhoto'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface IServicesBlockHeaderRichDescriptionPhotoFields {
  /** header */
  header?: string | undefined

  /** description */
  description?: Document | undefined

  /** photo */
  photo?: Asset | undefined

  /** description extended */
  descriptionExtended?: Document | undefined
}

export interface IServicesBlockHeaderRichDescriptionPhoto
  extends Entry<IServicesBlockHeaderRichDescriptionPhotoFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'servicesBlockHeaderRichDescriptionPhoto'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITagFields {
  /** tag name */
  tagName: string
}

export interface ITag extends Entry<ITagFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tag'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITechnologyFields {
  /** title */
  title: string

  /** icon */
  icon: Asset

  /** technology element */
  technologyElement: IServicesTechnologiesElement[]
}

export interface ITechnology extends Entry<ITechnologyFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'technology'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITestimonialFields {
  /** title */
  title: string

  /** caseStudy */
  caseStudy?: ICaseStudy | undefined

  /** body */
  body: string

  /** author */
  author?: IAuthor | undefined

  /** logo */
  logo: Asset

  /** quote icon */
  quoteIcon: Asset
}

export interface ITestimonial extends Entry<ITestimonialFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'testimonial'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITextBlockFields {
  /** header */
  header: string

  /** content */
  content: string
}

/** A piece of text to be organized into TextBlockGrid component. */

export interface ITextBlock extends Entry<ITextBlockFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'textBlock'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITextBlockGridFields {
  /** title */
  title?: string | undefined

  /** blocks */
  blocks?: ITextBlock[] | undefined
}

/** Organize short snippets of text in two columns (on wide screens) and one-by-one (on mobile) */

export interface ITextBlockGrid extends Entry<ITextBlockGridFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'textBlockGrid'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITileFields {
  /** title */
  title?: string | undefined

  /** content */
  content: Document

  /** lg */
  lg: number

  /** md */
  md: number

  /** sm */
  sm: number

  /** xs */
  xs: number
}

export interface ITile extends Entry<ITileFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tile'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export interface ITilesCollectionFields {
  /** title */
  title?: string | undefined

  /** tiles */
  tiles?: ITile[] | undefined
}

export interface ITilesCollection extends Entry<ITilesCollectionFields> {
  sys: {
    id: string
    type: string
    createdAt: string
    updatedAt: string
    locale: string
    contentType: {
      sys: {
        id: 'tilesCollection'
        linkType: 'ContentType'
        type: 'Link'
      }
    }
  }
}

export type CONTENT_TYPE =
  | 'actionButton'
  | 'anchor'
  | 'author'
  | 'backgroundImage'
  | 'blogPost'
  | 'blogTag'
  | 'businessVertical'
  | 'caseStudy'
  | 'caseStudyTestimonial'
  | 'codeSnippet'
  | 'currentOpenings'
  | 'deliveryProcess'
  | 'downloadButton'
  | 'gain'
  | 'gridBlock'
  | 'hubspotForm'
  | 'iconCard'
  | 'iconCardsCollection'
  | 'iconHeadlineDescription'
  | 'image'
  | 'imagesGrid'
  | 'imageSlider'
  | 'instagramPostReference'
  | 'instagramPosts'
  | 'jobPage'
  | 'jobPosting'
  | 'landingPage'
  | 'linkImage'
  | 'numberHeadlineDescription'
  | 'page'
  | 'personCard'
  | 'policy'
  | 'process'
  | 'services'
  | 'services-technologies-element'
  | 'servicesBanner'
  | 'servicesBannerItem'
  | 'servicesBlockHeaderDescription'
  | 'servicesBlockHeaderDescriptionPhoto'
  | 'servicesBlockHeaderRichDescriptionPhoto'
  | 'tag'
  | 'technology'
  | 'testimonial'
  | 'textBlock'
  | 'textBlockGrid'
  | 'tile'
  | 'tilesCollection'

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
