export enum TaskStatus {
    RUNNING = "RUNNING",
    PROVISIONING = "PROVISIONING",
    PENDING = "PENDING",
    ACTIVATING = "ACTIVATING",
    DEACTIVATING = "DEACTIVATING",
    STOPPING = "STOPPING",
    DEPROVISIONING = "DEPROVISIONING",
    STOPPED = "STOPPED"
}