name: Run analyzer tests on push

on: [push]

jobs:
  tests:
    runs-on: ubuntu-20.04
    container: node:14.17-buster

    steps:
      - uses: actions/checkout@v1

      - name: Cache NPM dependencies
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-cache-

      - name: Upgrade NPM
        run: npm install -g npm

      - name: Install npm dependencies
        run: npm ci @evm-debuger/analyzer

      - name: Run tests
        run: npm run analyzer:test
