name: Issue workflow

on:
  issues:
    types: [ opened, assigned, closed ]

jobs:
  move_issue_after_opened:
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        if: github.event.action == 'opened'
        with:
          project: EVM debugger
          column: Backlog
          repo-token: ${{ secrets.GH_TOKEN }}

  move_issue_after_closed:
    runs-on: ubuntu-latest
    if: github.event.action == 'closed'
    steps:
      - uses: alex-page/github-project-automation-plus@v0.8.1
        with:
          project: EVM debugger
          column: Done
          repo-token: ${{ secrets.GH_TOKEN }}
